### ISSUE TITLE
No such file or directory (os error 2) in Wiki.luau

### ISSUE THREAD

**Issue by metalbracket** [ArvidSilverlock/Pilot.lua-Luau-LSP#30]
Um this is my first issue so it may not be so good.

I tried to use `lune run pilot-generate -- --wiki` and it failed, because it is trying to remove a file that is not existing, which errors on my system.

OS: macos
Output: `✔ Accessing ROBLOX documentation took 467.22 ms
✔ Parsing Pilot.lua documentation took 31.00 ms

✔ Generating definition took 6.38 ms
✔ Generating documentation took 14.61 ms
✔ Generating modules took 3.62 ms
✔ Generating vscode took 1.29 ms
No such file or directory (os error 2)
[Stack Begin]
	Script '[C]'
	Script '__mlua_async_poll', Line 4
	Script '.lune/generate/generators/Wiki.luau', Line 157
	Script '.lune/generate/generators/Wiki.luau', Line 167
	Script '.lune/pilot-generate', Line 65
	Script '.lune/pilot-generate', Line 120
[Stack End]
`

What i did so it fixed:
```		
155 if typeof(value) == "table" then
			if fs.isDir(`{path}/{name}`) then
				fs.removeDir(`{path}/{name}`)
			end
			fs.writeDir(`{path}/{name}`)
			recursiveWrite(value, `{path}/{name}`)
		else
			if fs.isFile(`{path}/{name}`) then
				fs.writeFile(`{path}/{name}.md`, value)
			end
		end```

**Comment by ArvidSilverlock** [comment]
Looks like my file system is less strict than yours, and lets me remove non existent directories (seems bizarre, we are both running macos, though, I am running catalina).

Your solution seems sound, besides the `if fs.isFile(`{path}/{name}`) then` check (would this not just prevent all generation from occurring?). I have implemented the first half of the solution, but excluded this aspect.
