### ISSUE TITLE
Lua LSP failing

### ISSUE THREAD

**Issue by metalbracket** [ArvidSilverlock/Pilot.lua-Luau-LSP#31]
when i try to use vscode with the lsp, the luau lsp server gives this error:
#Failed to read definitions file /Users/pc/luau/Pilot.lua-Luau-LSP/workspace/types/global.d.luau. Extended types will not be provided

Error was at line 257:
`export type InstanceProperties = { Archivable: boolean?, Name: string?, Parent: Instance? } & ObjectProperties`

i thought it was a typo and i changed ObjectProperties to GuiObjectPropertys but then there were way more errors:

lines affected: 265, 2915-3110

**Comment by ArvidSilverlock** [comment]
Roblox recently added a new base class to all instances, `Object`. This new base class has no writable properties, which previously didn't exist (as `Instance` was the base class, and you can write several properties within it).

This should be resolved now.
