### ISSUE TITLE
[Feature Request] Selene globals generation

### ISSUE THREAD

**Issue by lrockreal** [ArvidSilverlock/Pilot.lua-Luau-LSP#4]
For codebases that use [selene](https://github.com/Kampfkarren/selene) for linting

Format: https://kampfkarren.github.io/selene/usage/std.html

**Comment by lrockreal** [comment]
@sweetboss12512

**Comment by sweetboss12512** [comment]
https://github.com/ArvidSilverlock/Pilot.lua-Luau-LSP/pull/9
